// src/components/characters.tsx
import React, { ReactElement, useContext } from "react";
import { ContextSettings } from '../context/contextSettings';
const shortid = require("shortid");

let personages = [
  "golemIce",
  "golemSwamp",
  "golemLava",
  "goblin",
  "troll",
  "orc",
  "fallenAngel",
  "reaper"
];

export default (): ReactElement => {

  let [settings, setSettings] = useContext(ContextSettings);

  let golems = shuffleArray(personages);

  if (settings.animation && !settings.turnOffAnimation) {

    let appearingPortal = (settings.appearingPortal === 1) ? 2 : 0;
    let delay = 0.5 + appearingPortal;
    let ms = 0.50;
    let jump = 1.40 + appearingPortal + 0.65;
    let rotate = 1.85 + appearingPortal + 0.65;
    let sizeReduction = 2.40 + appearingPortal + 0.65;
    let reduction = 2.45 + appearingPortal + 0.65;

    settings.stack.splice(-1, 1);

    let characters = settings.stack.map((icon, k: number) => {
      if (k !== 0) {
        (delay += ms).toPrecision(3);
        (jump += ms).toPrecision(2);
        (rotate += ms).toPrecision(2);
        (sizeReduction += ms).toPrecision(2);
        (reduction += ms).toPrecision(2);
      }

      let el = golems[k];
      return (
        <div
          key={shortid.generate()}
          className="character"
          id={el}
          style={{
            animation: `golem 0.55s linear ${delay}s forwards,
                     ${el}Running 0.35s steps(12) infinite,
                     golemMove 2s linear ${delay}s forwards,
                     golemJump 0.55s ease-in-out ${jump}s forwards,
                     golemRotate 0.55s linear ${rotate}s forwards,
                     sizeReduction 0.95s linear ${sizeReduction}s forwards,
                     reduction 1.25s linear ${reduction}s forwards`
          }}
          onAnimationEnd={e => {
            if (k == settings.stack.length - 1 && e.animationName == "reduction") {
              setSettings({
                ...settings,
                animation: false,
                wizardStatus: "idle",
                openPortal: true,
                appearingPortal: 2,
                getLinks: true
              });
            }
          }}>
          <div className={`sign ${icon}`}
            style={
              { animation: `rotateSign 0.15s ease ${rotate}s forwards` }
            }
          ></div>
        </div>
      );
    });
    return <>{characters}</>;
  }
  else {
    return (<></>)
  }

};

function shuffleArray(arr: string[]): string[] {
  return arr.sort(() => Math.random() - 0.5);
}

// astro+svelte/pc/src/pages/characters.svelte
<script>
  import { ContextSettings } from "../stores/wizard-context.js";
  import Character from "./character.svelte";

  /**
   * @type {string[]}
   */
  var personages = [
    "golemIce",
    "golemSwamp",
    "golemLava",
    "goblin",
    "troll",
    "orc",
    "fallenAngel",
    "reaper",
  ];
  /**
   * @param {string[]} arr
   * @returns {string[]}
   */
  var shuffleArray = (arr) => arr.sort(() => Math.random() - 0.5);
  /**
   * @type {object}
   */
  var obj = {};
  /**
   * @type {string[]}
   */
  var golems;

  $: if ($ContextSettings.animation && !$ContextSettings.turnOffAnimation) {
    golems = shuffleArray(personages);
    obj.appearingPortal = $ContextSettings.appearingPortal === 1 ? 2 : 0;
    obj.delay = 0.5 + obj.appearingPortal;
    obj.ms = 0.5;
    obj.jump = 1.4 + obj.appearingPortal + 0.65;
    obj.rotate = 1.85 + obj.appearingPortal + 0.65;
    obj.sizeReduction = 2.4 + obj.appearingPortal + 0.65;
    obj.reduction = 2.45 + obj.appearingPortal + 0.65;
  }
</script>

{#if $ContextSettings.animation && !$ContextSettings.turnOffAnimation}
  {#each $ContextSettings.stack as icon, k}
    <Character id={golems[k]} {...obj} {icon} {k} />
    {#if k === $ContextSettings.stack.length}
      {(obj = {})}
    {/if}
  {/each}
{/if}
