// src/mobileVersion/components/UI/btnClose.tsx
import React, { ReactElement, useContext } from "react";
import { ContextSettings } from '../../context/context';
import styled from 'styled-components';
import bg from '../../public/img/btnclose.png';

const BtnClose = styled.div`
    width: 40px;
    height: 40px;
    background: url(${bg}) no-repeat;
    background-size:contain;
    position:absolute;
    z-index: 5;
    top:0px;
    right:0px;
`;
export default (): ReactElement => {
    let [settings, setSettings] = useContext(ContextSettings);
    return (<BtnClose onClick={() => setSettings({ ...settings, go: true, close: true })} />);
};

// astro+svelte/mobile/src/components/UI/btnClose.svelte
<!-- svelte-ignore a11y-click-events-have-key-events -->
<script>
  import { ContextSettings } from "../../stores/settings-context.js";

  /**
   *
   * @param {string} category
   * @returns {import("../../stores/settings-context.js").infoSettings}
   */
  var close = () =>
    ContextSettings.update((settings) => ({
      ...settings,
      go: true,
      close: false,
    }));
</script>

<div class="btn_close" on:click={close} />

<style>
  .btn_close {
    width: 40px;
    height: 40px;
    background: url("/img/btnclose.png") no-repeat;
    background-size: contain;
    position: absolute;
    z-index: 5;
    top: 0px;
    right: 0px;
  }
</style>
