// react/src/mobileVersion/components/UI/panel.tsx
import React, { Suspense, ReactElement, useContext } from "react";
import { ContextSettings } from '../../context/context';
import styled from 'styled-components';
import BtnClose from './btnClose';

const LazyComponents = {
    about: React.lazy(() => import('../categories/about')),
    contacts: React.lazy(() => import('../categories/contacts')),
    skills: React.lazy(() => import('../categories/skills')),
    stacks: React.lazy(() => import('../categories/stack'))
}

const Panel = styled.div`
    width: 100%;
    min-height: 100vh;
    margin-left: ${(props) => (props.go && !props.close) ? "0vw" : "-100vw"};
    background-color: rgba(68, 46, 104, 0.75);
    position:absolute;
    transition: all ease .55s;
    z-index: 2;
    top:0px;
`;

export default (props): ReactElement => {
    let [settings] = useContext(ContextSettings);
    const Category = LazyComponents[settings.category];
    return (
        <Panel {...settings}>
            <BtnClose />
            <Suspense fallback={<></>}>
                <Category />
            </Suspense>
        </Panel>
    );
}

// astro+svelte/mobile/src/components/categories/panel.svelte
<script>
  import { ContextSettings } from "../../stores/settings-context.js";
  import BtnClose from "../UI/btnClose.svelte";
  import Contacts from "./contacts.svelte";
  import Skills from "./skills.svelte";
  import Stack from "./stack.svelte";

/**
 * @typedef ListOfComponents
 * @type {object}
 * @property {Skills} Skills
 * @property {Contacts} Contacts
 * @property {Stack} Stack
 */

 /** @type {ListOfComponents} */
  var components = {
    Skills,
    Contacts,
    Stack
  };
</script>

<div
  class="panel"
  style:margin-left={$ContextSettings.go && !$ContextSettings.close
    ? "-100vw"
    : "0vw"}
>
  <BtnClose />
  <svelte:component this={components[$ContextSettings.category]} />
</div>

<style>
  .panel {
    width: 100%;
    min-height: 100vh;
    background-color: rgba(68, 46, 104, 0.75);
    position: absolute;
    transition: all ease 0.55s;
    z-index: 2;
    top: 0px;
    overflow: scroll;
  }
</style>
